"""Helpers for source-based manual score versions.

The browser edits the visible target notation.  These helpers map bounded pitch
corrections back to the corresponding canonical source events so the target is
always regenerated by the deterministic transposer.  Python 3.6 compatible.
"""
import os
import re

from score_transposition import child, local, pitch_number, value


LETTERS = "CDEFGAB"
NATURALS = (0, 2, 4, 5, 7, 9, 11)
EVENT_ID = re.compile(r"^p([1-9][0-9]*)-m([1-9][0-9]*)-n([1-9][0-9]*)$")


def canonical_source_musicxml(job_dir):
    path = os.path.join(job_dir, "scores", "source", "canonical-source.musicxml")
    return path if os.path.isfile(path) and not os.path.islink(path) else None


def event_nodes(root):
    nodes = {}
    for part_index, part in enumerate((node for node in root if local(node.tag) == "part"), 1):
        for measure_index, measure in enumerate(
                (node for node in part if local(node.tag) == "measure"), 1):
            for note_index, note in enumerate(
                    (node for node in measure if local(node.tag) == "note"), 1):
                nodes["p%s-m%s-n%s" % (part_index, measure_index, note_index)] = note
    return nodes


def _pitch(node):
    pitch = child(node, "pitch") if node is not None else None
    if pitch is None:
        return None
    return {
        "step": value(pitch, "step"),
        "alter": int(value(pitch, "alter", "0")),
        "octave": int(value(pitch, "octave")),
    }


def target_pitch_changes_to_source(source_root, target_root, changes, semitones):
    """Invert visible target pitch corrections onto matching source events."""
    source_nodes, target_nodes = event_nodes(source_root), event_nodes(target_root)
    if set(source_nodes) != set(target_nodes):
        raise ValueError("源谱与目标谱事件结构不一致，不能安全回写源谱")
    mapped = []
    for change in changes:
        if not isinstance(change, dict) or set(change) != {"eventId", "pitch"}:
            raise ValueError("源谱回写只接受音高修改")
        event_id = change.get("eventId")
        if not isinstance(event_id, str) or not EVENT_ID.fullmatch(event_id):
            raise ValueError("音符编号无效，请重新载入")
        source_pitch = _pitch(source_nodes.get(event_id))
        target_pitch = _pitch(target_nodes.get(event_id))
        new_target = change.get("pitch")
        if source_pitch is None or target_pitch is None:
            raise ValueError("休止符或无固定音高事件不能作为音高回写")
        if (not isinstance(new_target, dict) or
                set(new_target) != {"step", "alter", "octave"}):
            raise ValueError("音高格式无效")
        source_letter = source_pitch["octave"] * 7 + LETTERS.index(source_pitch["step"])
        target_letter = target_pitch["octave"] * 7 + LETTERS.index(target_pitch["step"])
        new_target_letter = int(new_target["octave"]) * 7 + LETTERS.index(new_target["step"])
        source_letter_new = new_target_letter - (target_letter - source_letter)
        source_octave, source_step_index = divmod(source_letter_new, 7)
        source_midi = pitch_number(
            new_target["step"], new_target["alter"], new_target["octave"]) - int(semitones)
        natural_midi = 12 * (source_octave + 1) + NATURALS[source_step_index]
        source_alter = source_midi - natural_midi
        if source_alter not in (-2, -1, 0, 1, 2) or not 0 <= source_octave <= 9:
            raise ValueError("这项目标音高无法安全还原为源谱拼写，请下载 MusicXML 编辑")
        mapped.append({
            "eventId": event_id,
            "pitch": {"step": LETTERS[source_step_index],
                      "alter": source_alter, "octave": source_octave},
        })
    return mapped


def assert_target_pitch_changes(root, changes):
    """Prove regenerated target pitches equal the user's visible choices."""
    nodes = event_nodes(root)
    for change in changes:
        if set(change) != {"eventId", "pitch"}:
            continue
        actual = _pitch(nodes.get(change["eventId"]))
        if actual != change["pitch"]:
            raise ValueError("源谱回写后的目标音高与所选结果不一致，已拒绝生成")
    return True
