import { BarChart3, FileText, LogOut, MessageSquare, Music2, Pin, Save, ShieldCheck, Trash2, Upload } from 'lucide-react';
import { ChangeEvent, useEffect, useState } from 'react';
import { apiRequest } from '../services/api';
import { defaultContent, type EditableContent } from '../context/ContentContext';
import type { CampusPhoto } from '../types';
import { RestAnnotationPanel } from '../components/RestAnnotationPanel';

type Tab = 'analytics' | 'content' | 'messages' | 'rest-annotations';
type MetricRow = { label: string; value: number };
type Analytics = { days: number; views: number; visitors: number; sessions: number; todayViews: number; trend: MetricRow[]; pages: MetricRow[]; referrers: MetricRow[]; devices: MetricRow[] };
type AdminReply = { id: string; nickname: string; content: string; created_at: string; status: string; report_count: number; like_count: number };
type AdminMessage = AdminReply & { email: string; pinned: number; replies: AdminReply[] };

export default function AdminPage() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { apiRequest<{ authenticated: boolean }>('/api/admin/session').then((r) => setAuthenticated(r.authenticated)).catch(() => setAuthenticated(false)); }, []);
  const login = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    try { await apiRequest('/api/admin/login', { method: 'POST', body: JSON.stringify({ password }) }); setAuthenticated(true); }
    catch (caught) { setError(caught instanceof Error ? caught.message : '登录失败'); }
    finally { setBusy(false); }
  };
  if (authenticated === null) return <div className="grid min-h-screen place-items-center">正在验证登录状态…</div>;
  if (!authenticated) return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-slate-700 bg-slate-900 p-8 shadow-2xl"><ShieldCheck className="text-blue-400" size={38} /><h1 className="mt-5 text-3xl font-black">网站管理后台</h1><p className="mt-2 text-sm text-slate-400">此页面仅供站长使用。</p><label className="mt-8 block text-sm font-semibold">管理密码<input type="password" autoFocus className="mt-2 min-h-12 w-full rounded-xl border border-slate-700 bg-slate-950 px-4" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="mt-3 text-sm text-red-400">{error}</p>}<button disabled={busy} className="button-primary mt-5 w-full">{busy ? '正在登录…' : '登录'}</button></form></main>;
  return <AdminConsole onLogout={() => setAuthenticated(false)} />;
}

function AdminConsole({ onLogout }: { onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>('analytics');
  const logout = async () => { await apiRequest('/api/admin/logout', { method: 'POST', body: '{}' }); onLogout(); };
  return <main className="min-h-screen bg-slate-100 text-slate-900 dark:bg-slate-950 dark:text-white"><header className="sticky top-0 z-20 border-b bg-white/95 px-5 py-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/95"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><div><strong className="text-xl">ZHANG. 管理后台</strong><p className="text-xs text-slate-500">内容修改保存后立即生效，无需重新打包</p></div><nav className="flex flex-wrap gap-2">{([['analytics','数据统计',BarChart3],['content','内容管理',FileText],['messages','留言管理',MessageSquare],['rest-annotations','乐谱结构标注',Music2]] as const).map(([value,label,Icon]) => <button key={value} onClick={() => setTab(value)} className={`inline-flex min-h-10 items-center gap-2 rounded-xl px-4 text-sm font-semibold ${tab === value ? 'bg-blue-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}><Icon size={16}/>{label}</button>)}<button onClick={() => void logout()} className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm text-slate-500"><LogOut size={16}/>退出</button></nav></div></header><div className="mx-auto max-w-[1500px] p-5 py-8">{tab === 'analytics' && <AnalyticsPanel />}{tab === 'content' && <ContentPanel />}{tab === 'messages' && <MessagesPanel />}{tab === 'rest-annotations' && <RestAnnotationPanel />}</div></main>;
}

function AnalyticsPanel() {
  const [days, setDays] = useState(30); const [data, setData] = useState<Analytics | null>(null);
  useEffect(() => { apiRequest<{ data: Analytics }>(`/api/admin/analytics?days=${days}`).then(r => setData(r.data)); }, [days]);
  if (!data) return <p>正在加载统计数据…</p>;
  return <section><div className="flex items-end justify-between"><div><p className="eyebrow">PRIVATE ANALYTICS</p><h1 className="text-3xl font-black">访客数据统计</h1></div><select className="rounded-xl border bg-transparent px-3 py-2" value={days} onChange={e => setDays(Number(e.target.value))}><option value={7}>近 7 天</option><option value={30}>近 30 天</option><option value={90}>近 90 天</option><option value={365}>近 1 年</option></select></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['浏览量',data.views],['独立访客',data.visitors],['访问会话',data.sessions],['今日浏览',data.todayViews]].map(([label,value]) => <article className="rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900" key={label}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-4xl">{value}</strong></article>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Rank title="热门页面 / 项目" rows={data.pages}/><Rank title="访客来源" rows={data.referrers}/><Rank title="设备类型" rows={data.devices}/><Rank title="每日访问趋势" rows={data.trend.slice(-14)}/></div></section>;
}

function Rank({ title, rows }: { title: string; rows: MetricRow[] }) {
  const max = Math.max(1, ...rows.map(r => r.value));
  return <section className="rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">{title}</h2><div className="mt-5 space-y-4">{rows.length ? rows.map(row => <div key={row.label}><div className="flex justify-between gap-4 text-sm"><span className="truncate">{row.label}</span><strong>{row.value}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(4,row.value/max*100)}%`}}/></div></div>) : <p className="text-sm text-slate-500">暂无数据，访客访问后会自动记录。</p>}</div></section>;
}

function ContentPanel() {
  const [content, setContent] = useState<EditableContent>(structuredClone(defaultContent));
  const [selectedProject, setSelectedProject] = useState(0); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { apiRequest<{ data: EditableContent | null }>('/api/content').then(r => r.data && setContent(r.data)); }, []);
  const profile = content.siteData; const project = content.projects[selectedProject];
  const save = async () => { setSaving(true); setNotice(''); try { const r = await apiRequest<{message:string}>('/api/admin/content',{method:'PUT',body:JSON.stringify(content)}); setNotice(r.message); } catch(e) { setNotice(e instanceof Error?e.message:'保存失败'); } finally { setSaving(false); } };
  const setProfile = (key: keyof typeof profile, value: string) => setContent(c => ({...c,siteData:{...c.siteData,[key]:value}}));
  const setProject = (key: string, value: string | string[]) => setContent(c => ({...c,projects:c.projects.map((p,i)=>i===selectedProject?{...p,[key]:value}:p)}));
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">RUNTIME CONTENT</p><h1 className="text-3xl font-black">个人网站内容管理</h1></div><div className="flex items-center gap-3">{notice && <span className="text-sm text-slate-500">{notice}</span>}<button onClick={() => void save()} disabled={saving} className="button-primary"><Save size={17}/>{saving?'保存中…':'保存并立即发布'}</button></div></div><div className="mt-7 grid gap-6 xl:grid-cols-2"><EditorCard title="个人介绍"><Field label="姓名" value={profile.name} onChange={v=>setProfile('name',v)}/><Field label="身份 / 专业" value={profile.identity} onChange={v=>setProfile('identity',v)}/><Field label="首页简介" value={profile.intro} onChange={v=>setProfile('intro',v)} area/><Field label="邮箱" value={profile.email} onChange={v=>setProfile('email',v)}/><Field label="地点" value={profile.location} onChange={v=>setProfile('location',v)}/></EditorCard><EditorCard title="项目文字"><select className="mb-4 min-h-11 w-full rounded-xl border bg-transparent px-3" value={selectedProject} onChange={e=>setSelectedProject(Number(e.target.value))}>{content.projects.map((p,i)=><option key={p.id} value={i}>{p.title}</option>)}</select>{project && <><Field label="项目名称" value={project.title} onChange={v=>setProject('title',v)}/><Field label="项目摘要" value={project.summary} onChange={v=>setProject('summary',v)} area/><Field label="我的职责" value={project.role} onChange={v=>setProject('role',v)} area/><Field label="项目背景" value={project.background} onChange={v=>setProject('background',v)} area/><Field label="技术方案" value={project.solution} onChange={v=>setProject('solution',v)} area/><Field label="项目成果" value={project.result} onChange={v=>setProject('result',v)} area/><Field label="技术标签（逗号分隔）" value={project.tech.join(', ')} onChange={v=>setProject('tech',v.split(/[,，]/).map(s=>s.trim()).filter(Boolean))}/><Field label="封面图片地址" value={project.cover ?? ''} onChange={v=>setProject('cover',v)}/></>}</EditorCard><ExperienceEditor content={content} setContent={setContent}/><HonorEditor content={content} setContent={setContent}/><UploadEditor setContent={setContent} selectedProject={selectedProject}/></div></section>;
}

function EditorCard({title,children}:{title:string;children:React.ReactNode}) { return <section className="rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-5 text-xl font-bold">{title}</h2>{children}</section>; }
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}) { return <label className="mb-4 block text-sm font-semibold"><span className="mb-2 block">{label}</span>{area?<textarea className="min-h-24 w-full rounded-xl border bg-transparent p-3 font-normal leading-6" value={value} onChange={e=>onChange(e.target.value)}/>:<input className="min-h-11 w-full rounded-xl border bg-transparent px-3 font-normal" value={value} onChange={e=>onChange(e.target.value)}/>}</label>; }

function ExperienceEditor({content,setContent}:{content:EditableContent;setContent:React.Dispatch<React.SetStateAction<EditableContent>>}) { return <EditorCard title="学习与经历">{content.experiences.map((item,index)=><details className="mb-3 rounded-xl border p-4" key={`${item.organization}-${index}`}><summary className="cursor-pointer font-bold">{item.organization}</summary><div className="mt-4"><Field label="时间" value={item.period} onChange={v=>setContent(c=>({...c,experiences:c.experiences.map((x,i)=>i===index?{...x,period:v}:x)}))}/><Field label="机构" value={item.organization} onChange={v=>setContent(c=>({...c,experiences:c.experiences.map((x,i)=>i===index?{...x,organization:v}:x)}))}/><Field label="身份" value={item.role} onChange={v=>setContent(c=>({...c,experiences:c.experiences.map((x,i)=>i===index?{...x,role:v}:x)}))}/><Field label="经历描述" value={item.work} area onChange={v=>setContent(c=>({...c,experiences:c.experiences.map((x,i)=>i===index?{...x,work:v}:x)}))}/><Field label="收获" value={item.growth} area onChange={v=>setContent(c=>({...c,experiences:c.experiences.map((x,i)=>i===index?{...x,growth:v}:x)}))}/></div></details>)}</EditorCard>; }
function HonorEditor({content,setContent}:{content:EditableContent;setContent:React.Dispatch<React.SetStateAction<EditableContent>>}) { const update=(index:number,key:string,value:string)=>setContent(c=>({...c,honors:c.honors.map((h,i)=>i===index?{...h,[key]:value}:h)})); return <EditorCard title="荣誉与成果">{content.honors.map((h,index)=><details className="mb-3 rounded-xl border p-4" key={`${h.title}-${index}`}><summary className="cursor-pointer font-bold">{h.year} · {h.title}</summary><div className="mt-4"><Field label="奖项名称" value={h.title} onChange={v=>update(index,'title',v)}/><Field label="日期" value={h.year} onChange={v=>update(index,'year',v)}/><Field label="级别" value={h.level} onChange={v=>update(index,'level',v)}/><Field label="说明" value={h.description} area onChange={v=>update(index,'description',v)}/><Field label="证书图片地址" value={h.image} onChange={v=>update(index,'image',v)}/></div></details>)}</EditorCard>; }

function UploadEditor({setContent,selectedProject}:{setContent:React.Dispatch<React.SetStateAction<EditableContent>>;selectedProject:number}) { const [file,setFile]=useState<File|null>(null); const [target,setTarget]=useState('project'); const [caption,setCaption]=useState(''); const [busy,setBusy]=useState(false); const upload=async()=>{if(!file)return;setBusy(true);try{const data=await file.arrayBuffer();let binary='';new Uint8Array(data).forEach(b=>binary+=String.fromCharCode(b));const r=await apiRequest<{data:{url:string}}>('/api/admin/upload',{method:'POST',body:JSON.stringify({name:file.name,type:file.type,data:btoa(binary)})});const photo:CampusPhoto={src:r.data.url,alt:caption||file.name,caption:caption||file.name};setContent(c=>{if(target==='project')return{...c,projects:c.projects.map((p,i)=>i===selectedProject?{...p,photos:[...(p.photos||[]),photo]}:p)};const key=target as keyof EditableContent['galleries'];return{...c,galleries:{...c.galleries,[key]:[...c.galleries[key],photo]}}});setFile(null);setCaption('');}finally{setBusy(false)}}; return <EditorCard title="照片上传"><p className="mb-4 text-sm leading-6 text-slate-500">上传后会加入所选项目或经历相册，再点击页面顶部“保存并立即发布”。</p><select className="mb-4 min-h-11 w-full rounded-xl border bg-transparent px-3" value={target} onChange={e=>setTarget(e.target.value)}><option value="project">当前项目相册</option><option value="bashuPhotos">巴蜀中学经历</option><option value="mingyuePhotos">明月科创实验班经历</option><option value="roboconPhotos">GSing 战队经历</option><option value="campusPhotos">学生艺术团经历</option></select><Field label="图片说明" value={caption} onChange={setCaption}/><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} onClick={()=>void upload()} className="button-secondary mt-4"><Upload size={16}/>{busy?'上传中…':'上传图片'}</button></EditorCard>; }

function MessagesPanel() { const [status,setStatus]=useState('all'); const [items,setItems]=useState<AdminMessage[]>([]); const load=()=>apiRequest<{data:AdminMessage[]}>(`/api/admin/messages?status=${status}`).then(r=>setItems(r.data)); useEffect(()=>{void load()},[status]); const patch=async(type:'messages'|'replies',id:string,data:object)=>{await apiRequest(`/api/admin/${type}/${id}`,{method:'PATCH',body:JSON.stringify(data)});await load()}; const remove=async(type:'messages'|'replies',id:string)=>{if(!confirm('确定永久删除这条内容吗？'))return;await apiRequest(`/api/admin/${type}/${id}`,{method:'DELETE'});await load()}; return <section><div className="flex items-end justify-between"><div><p className="eyebrow">MODERATION</p><h1 className="text-3xl font-black">留言管理</h1></div><select className="rounded-xl border bg-transparent px-3 py-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部</option><option value="approved">已公开</option><option value="pending">待审核</option><option value="hidden">已隐藏</option></select></div><div className="mt-7 space-y-4">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{item.nickname}</strong><span className="ml-3 text-xs text-slate-500">{new Date(item.created_at).toLocaleString('zh-CN')} · {item.status} · {item.like_count} 赞 · {item.report_count} 举报</span><p className="mt-3 whitespace-pre-wrap leading-7">{item.content}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void patch('messages',item.id,{pinned:!item.pinned})} className="button-secondary px-3"><Pin size={15}/>{item.pinned?'取消置顶':'置顶'}</button><StatusButtons onStatus={s=>void patch('messages',item.id,{status:s})}/><button onClick={()=>void remove('messages',item.id)} className="button-secondary px-3 text-red-500"><Trash2 size={15}/>删除</button></div></div>{item.replies?.length>0&&<div className="mt-4 space-y-2 border-l-2 pl-4">{item.replies.map(reply=><div className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800" key={reply.id}><div className="flex flex-wrap justify-between gap-3"><div><strong className="text-sm">{reply.nickname}</strong><p className="mt-1 text-sm">{reply.content}</p><span className="text-xs text-slate-500">{reply.status} · {reply.like_count} 赞 · {reply.report_count} 举报</span></div><div className="flex gap-2"><StatusButtons onStatus={s=>void patch('replies',reply.id,{status:s})}/><button onClick={()=>void remove('replies',reply.id)} className="text-red-500"><Trash2 size={16}/></button></div></div></div>)}</div>}</article>)}{!items.length&&<p className="rounded-2xl border p-10 text-center text-slate-500">当前没有留言。</p>}</div></section>; }
function StatusButtons({onStatus}:{onStatus:(s:string)=>void}) { return <div className="flex overflow-hidden rounded-lg border text-xs"><button className="px-2 py-2 text-emerald-600" onClick={()=>onStatus('approved')}>公开</button><button className="border-l px-2 py-2 text-amber-600" onClick={()=>onStatus('pending')}>待审</button><button className="border-l px-2 py-2 text-slate-500" onClick={()=>onStatus('hidden')}>隐藏</button></div>; }
